### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by joesweeny** [statistico/statistico-web-platform#68]
- [x] Treat percentage based stats differently to others i.e. no display of total/sum for possession and passes accuracy

- [x] Implement refresh icon for 500 responses 

~~Display ! icon if any values returned contain a null value~~

- [x] Add fixture data to graph tooltips

- [x] Determine why null values are not accounted for in counts but are in graphs

- [x] Add tooltip for count / graph toogle (use better count icon)

- [x] Refactor counts into dedicated components

- [x] Improve graph size handling to be responsive to screen size. Currently displaying 2 per row, want to keep that for bigger screens too

~~Do not show `Opponent` toggle in counts view~~

- [ ] Assess implementation - am I happy with how each component is handled? Am I happy with component sizes?

- [x] Add fixtures dates as X axis keys 

- [x] Do not adjust height when hiding filters...make graph/counts grow
